language: node_js
node_js:
  - stable
install:
  - npm install
script:
  - npm run build
  - npm run coverage
  - npm run report
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
